version: '3'
services:
  node1:
    build: ./Node1
    container_name: "node1"
    hostname: "node1"
    depends_on:
      - consul
  node2:
    build: ./Node2
    hostname: "node2"
    depends_on:
      - consul
  consul:
    image: "consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "agent -server -bootstrap -ui -disable-host-node-id -client 0.0.0.0"