version: '3'
services:
  node1:
    build: ./Node1
    hostname: "node1"
    depends_on:
      - consul
  # node2:
  #   build: ./Node2
  #   hostname: "node2"
  #   depends_on:
  #     - consul
  #   ports:
  #     - "12000:12000"
  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap -ui-dir /ui"